version: 0.2

phases:
  install:
    commands:
      - echo Installing node modules...
      - npm install
  # pre_build:
  #   commands:
  #     - echo Installing source NPM dependencies...
  #     - npm install unit.js
  # build:
  #   commands:
  #     - echo Build started on `date`
  #     - echo Compiling the Node.js code
  #     - mocha app.js
  post_build:
      commands:
        - echo Build completed on `date`
        - mkdir build-output
        - cp -R Dockerfile app.js node_modules/ build-output
artifacts:
  files:
    - build-output/**/*